# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/surya/ece544/p2_wRTOS/p2_wRTOS.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
# IP: The module: 'embsys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/surya/ece544/p2_wRTOS/p2_wRTOS.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/surya/ece544/p2_wRTOS/p2_wRTOS.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
# IP: The module: 'embsys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/surya/ece544/p2_wRTOS/p2_wRTOS.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
