# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/n4DDRfpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_0_0/embsys_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_0_0 || ORIG_REF_NAME==embsys_clk_wiz_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_0 || ORIG_REF_NAME==embsys_lmb_bram_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_0_100M_0/embsys_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mig_7series_0_0/embsys_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_mig_7series_0_0 || ORIG_REF_NAME==embsys_mig_7series_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_mig_7series_0_81M_0/embsys_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==embsys_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_1_0 || ORIG_REF_NAME==embsys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodOLEDrgb_0_0 || ORIG_REF_NAME==embsys_PmodOLEDrgb_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodENC_0_0 || ORIG_REF_NAME==embsys_PmodENC_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_HB3_0_0/embsys_HB3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_HB3_0_0 || ORIG_REF_NAME==embsys_HB3_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4IO_0_0/embsys_nexys4IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_nexys4IO_0_0 || ORIG_REF_NAME==embsys_nexys4IO_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_11/embsys_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_11 || ORIG_REF_NAME==embsys_auto_pc_11} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_us_0/embsys_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_us_0 || ORIG_REF_NAME==embsys_auto_us_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_us_1/embsys_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_us_1 || ORIG_REF_NAME==embsys_auto_us_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_us_2/embsys_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_us_2 || ORIG_REF_NAME==embsys_auto_us_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_0/embsys_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_0 || ORIG_REF_NAME==embsys_auto_ds_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_0/embsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_0 || ORIG_REF_NAME==embsys_auto_pc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_1/embsys_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_1 || ORIG_REF_NAME==embsys_auto_ds_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_1/embsys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_1 || ORIG_REF_NAME==embsys_auto_pc_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_cc_0/embsys_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_cc_0 || ORIG_REF_NAME==embsys_auto_cc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_2/embsys_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_2 || ORIG_REF_NAME==embsys_auto_ds_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_2/embsys_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_2 || ORIG_REF_NAME==embsys_auto_pc_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_3/embsys_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_3 || ORIG_REF_NAME==embsys_auto_ds_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_3/embsys_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_3 || ORIG_REF_NAME==embsys_auto_pc_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_4/embsys_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_4 || ORIG_REF_NAME==embsys_auto_ds_4} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_4/embsys_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_4 || ORIG_REF_NAME==embsys_auto_pc_4} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_5/embsys_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_5 || ORIG_REF_NAME==embsys_auto_ds_5} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_5/embsys_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_5 || ORIG_REF_NAME==embsys_auto_pc_5} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_6/embsys_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_6 || ORIG_REF_NAME==embsys_auto_ds_6} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_6/embsys_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_6 || ORIG_REF_NAME==embsys_auto_pc_6} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_7/embsys_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_7 || ORIG_REF_NAME==embsys_auto_ds_7} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_7/embsys_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_7 || ORIG_REF_NAME==embsys_auto_pc_7} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_8/embsys_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_8 || ORIG_REF_NAME==embsys_auto_ds_8} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_8/embsys_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_8 || ORIG_REF_NAME==embsys_auto_pc_8} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_9/embsys_auto_ds_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_9 || ORIG_REF_NAME==embsys_auto_ds_9} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_9/embsys_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_9 || ORIG_REF_NAME==embsys_auto_pc_9} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_ds_10/embsys_auto_ds_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_ds_10 || ORIG_REF_NAME==embsys_auto_ds_10} -quiet] -quiet

# IP: bd/embsys/ip/embsys_auto_pc_10/embsys_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_auto_pc_10 || ORIG_REF_NAME==embsys_auto_pc_10} -quiet] -quiet

# XDC: bd/embsys/embsys_ooc.xdc
